### ISSUE TITLE
Add analytics for various actions throughout the app

### ISSUE THREAD

**Issue by rye** [StoDevX/AAO-React-Native#2045]
Specifically, we discussed analytics for #2032, but I'm thinking having little bits of reporting sprinkled about elsewhere might be another good idea.

I will come up with a list of stuff we don't seem to have that we should have at some point.

## Things

- [x] Login state (logged in, logged out, emphatically _not_ username)
- [x] ~~App resume vs. launch (#2211)~~
- [x] Disabled homescreen buttons
- [x] Presses of the "play stream" button (#2209)

**Comment by hawkrives** [comment]
https://github.com/StoDevX/AAO-React-Native/blob/dedae1e6864d347f6944edbda7e1ce0f5542a0fa/source/flux/parts/homescreen.js#L99-L117

for #2032 in particular

**Comment by hawkrives** [comment]
Login state

**Comment by drewvolz** [comment]
Is there anything still needed to be done here?
