### ISSUE TITLE
Tracking: Alternate Icon Ideas

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#2243]
This is a tracking issue for the second push on alternate icons. The first set of two icons is going out in v2.5. 

## Iconographical Ideas
- [x] Windmill
- [ ] MGM Lion (@hawkrives)
- [ ] Squirrel (@drewvolz)
- [ ] Pizza (@drewvolz)
- [ ] Water tower (lion silhouette on tower top) (@hawkrives)
- [ ] Circuit lion (@drewvolz)
- [ ] Boe Chapel structure (@hawkrives)
- [ ] "O" for Olaf (@drewvolz)
- [ ] UmYahYah square from new branding guidelines (@hawkrives)
- [ ] Something calligraphical/fancy? (@rye)

## Other Ideas
- Offer each as a full/multi-color basic icon
- Also offer six-ish other single-color-tint variants, for people who like to colorize their homescreens 
    - blue
    - red
    - green
    - gold
    - purple
    - pink

**Comment by drewvolz** [comment]
<details>
<summary>Circuit lion</summary>
<br>
<img src="https://avatars3.githubusercontent.com/u/29408373?s=200&v=4" />
</details>

**Comment by drewvolz** [comment]
I really enjoy [The Noun Project](https://thenounproject.com/)'s set of icons. We can even use them freely if we credit.

- [Water tower](https://thenounproject.com/search/?q=water%20tower)
- [Chapel](https://thenounproject.com/search/?q=chapel)
- [Pizza](https://thenounproject.com/search/?q=pizza)
- [Squirrel](https://thenounproject.com/search/?q=squirrel)

**Comment by hawkrives** [comment]
https://bl.ocks.org/hawkrives/raw/52076be27ca1bde0c0b83524ed8cd7bf/

I've got part of a skeleton for generating colorized versions of our icons; this will be even nicer when we have them as vectors, but this POC shows that we needen't always impose that restriction. :)

<details><summary>For longevity:</summary>

![result-oldmain](https://user-images.githubusercontent.com/464441/36069493-87e13338-0eb0-11e8-8d97-0bac5b959ad5.png)
![result-windmill](https://user-images.githubusercontent.com/464441/36069494-87f9440a-0eb0-11e8-96a3-b915db02d019.png)

</details>

<br/>

References for `feColorMatrix`: 

- https://stackoverflow.com/questions/14663252/matching-a-color-in-svg-with-fecolormatrix#14663343
- https://css-tricks.com/color-filters-can-turn-your-gray-skies-blue/
- http://paletton.com/#uid=13B0u0kwi++bu++hX++++rd++kX (for colors)
- https://stackoverflow.com/questions/21977929/match-colors-in-fecolormatrix-filter#21979654
- http://alistapart.com/article/finessing-fecolormatrix – I may need to re-read this one to get any value out of it
