### ISSUE TITLE
Hawken's Goals This Week

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#51]
- [x] Make everything pass eslint and run it automatically (#53)
- [x] Extract a reusable, simpler wrapper for the tabview screens
- [x] Use Drew's list view in the calendar
- [x] fix calendar loading on android (#89)
- [x] figure out the map on android bug (#27)
- [x] SIS financials view (part of #13)
- [x] SIS courses-by-term lists (other part of #13)
- [ ] Fix local building images on Android (#52)
- [ ] Transportation view (#15)
- [ ] fix alignment issues in the Android title bar

**Comment by elijahverdoorn** [comment]
Talk to me before doing the transportation view, I have some updated data relevant to that. (or I'm happy to do it myself)

**Comment by hawkrives** [comment]
If you put the data in the `transportation.json` file, I'll gladly use it 😉

**Comment by elijahverdoorn** [comment]
Ok. I intentionally want this view to be really simple, since we can't possibly cover all the modes of transport and we don't want to cover others. The biggest thing is the bus schedule and VanGo. We're not adding the Northfield Lines schedule, since they are not St. Olaf affiliated. Same for the rental cars and any kind of taxi.

**Comment by drewvolz** [comment]
Information on Green Bikes at the very least, since they are a St. Olaf group?

**Comment by elijahverdoorn** [comment]
Sure, Green bikes are a good idea, but since they stopped loaning them out to students in the spring I'm not sure of the status of the system. I'll investigate once I get back to campus and we can add it if they are loaning them out.

**Comment by drewvolz** [comment]
Are you sure they officially stopped? I checked one out a few weeks before graduation in May. [Also this](http://stolaf-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=01BRC_CCO_ALMA21287993030002971&indx=1&recIds=01BRC_CCO_ALMA21287993030002971&recIdxs=0&elementId=0&renderMode=poppedOut&displayMode=full&frbrVersion=&frbg=&&dscnt=0&scp.scps=scope%3A%2801BRC_SOC_COURSE%29%2Cscope%3A%28BRC_SOC-E-S%29%2Cscope%3A%28CCO_Print_S%29%2Cprimo_central_multiple_fe&vl%281UIStartWith0%29=contains&tb=t&vid=01BRC_SOC&mode=Basic&vl%28754424355UI0%29=any&srt=rank&tab=default_tab&dum=true&vl%28freeText0%29=greenbike&dstmp=1471395038910).

**Comment by elijahverdoorn** [comment]
They may have just been stopped the one time that I tried to check one out last semester. We can include the functionality and remove it if we're wrong, it's a two minute job.

**Comment by hawkrives** [comment]
ok people, take it to #15 lol

**Comment by elijahverdoorn** [comment]
One week later... Let's close this now that we have the milestones set up and can just assign current work, and talk about it in slack.
