### ISSUE TITLE
[Tracking] Navigation

### ISSUE THREAD

**Issue by drewvolz** [StoDevX/AAO-React-Native#6007]
Adding the new navigator APIs to the views.

iOS audit
- [x] SIS
  - [x] Balances
  - [x] Course search
  - [x] TES
  - [x] Open jobs
- [x] stoPrint
  - [x] Print jobs
  - [x] Release
  - [x] Printer list
  - [x] Error views
- [x] Menus
- [x] News
- [x] Building hours
  - [x] List
  - [x] Detail
  - [x] Favorite
  - [x] Report a problem
  - [x] Edit schedule
- [x] Calendar
  - [x] St Olaf
  - [x] Oleville
  - [x] Northfield
  - [x] Add to calendar
  - [x] Event Detail
- [x] Directory (link)
- [x] Directory (native)
  - [x] List
  - [x] Detail
- [x] Streaming media
  - [x] Events
  - [x] Webcams
  - [x] KSTO
  - [x] KRLX
  - [x] Show schedule    
- [x] Campus map (link)
- [x] Important contacts
  - [x] List
  - [x] Detail
- [x] Transportation
  - [x] Red
  - [x] Blue
  - [x] Olesgo
  - [x] Other modes
  - [x] Other modes detail
  - [x] Map
- [x] Campus Dictionary
  - [x] List
  - [x] Detail
  - [x] Search
  - [x] Report
- [x] Student Orgs
  - [x] List
  - [x] Detail
  - [x] Search
- [x] Moodle (link)
- [x] Oleville (link)
- [x] Report a problem
- [x] Settings
  - [x] Login
  - [x] Contact us
  - [x] FAQs
  - [x] Reset everything
  - [x] Change app icon
  - [x] Credits
  - [x] Privacy policy
  - [x] Legal
  - [x] Contributing (link)
- [x] Debug settings
  - [x] API tester
  - [x] Bon appetit picker
  - [x] Debug
  - [x] Send a sentry message
  - [x] Send a sentry exception
  - [x] Server url
