### ISSUE TITLE
E2E tests should test that every view is visible

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#6788]
extracted from #4013

---

Courtesy of @drewvolz, I'm adding a to-do list of things I should look at:

### Home
- [x] List of buttons

### Menus
- [x] Stav Hall → #6788
- [x] Cage → #6788
- [x] Pause → #6788
- [x] Burton → #6788
- [x] LDC → #6788
- [x] Weitz → #6788
- [x] Sayles → #6788
- [ ] Menu Item Detail

### SIS
- [x] Balances → #6788
- [x] Open Jobs List → #6788
- [ ] Open Jobs Detail

### Catalog
- [x] Course Search Home → #6788
- [ ] Course Search List
- [ ] Course Search Detail

### Building hours
- [x] Hours List → #6788
- [ ] Hours Detail
- [ ] Hours Problem Report
- [ ] Hours Schedule Editor

### Calendar
- [x] St. Olaf Calendar → #6788
- [x] Oleville Calendar → #6788
- [x] Northfield Calendar → #6788
- [ ] Calendar Event Detail

### Directory
- [x] Directory List → #6788
- [ ] Directory Contact Detail

### Streaming Media
- [x] Events calendar → #6788
- [x] Webcams → #6788
- [x] KSTO Radio → #4013
- [x] KRLX Radio → #4013
- [ ] Radio Schedule

### News
- [x] St. Olaf List → #6788
- [ ] Oleville List
- [ ] Mess List
- [ ] PoliticOle List (if we put it back in)
- [ ] KSTO List

### Map
- [x] Link to Browser → #6788

### Important Contacts
- [x] Contacts List → #6788
- [ ] Contacts Detail

### Transit
- [x] Express Bus
- [x] Red Line
- [x] Blue Line
- [x] Oles Go
- [x] Other Modes
- [ ] Other Modes Detail

### Dictionary
- [x] Dictionary List → #6788
- [ ] Dictionary Detail
- [ ] Dictionary Editor

### Student Orgs
- [x] Orgs List → #6788
- [ ] Orgs Detail

### stoPrint
- [ ] Printer List
- [ ] Print Job Release

### More
- [x] A-Z list → #6788

### Settings
- [x] List of settings
- [ ] Login
- [ ] Contact Us
- [ ] FAQs
- [ ] Reset
- [x] Icon Settings
- [ ] Credits
- [ ] Privacy Policy
- [ ] Legal
- [ ] Contributing (link to browser)

### Developer
- [ ] API Test
- [ ] BonApp Picker
- [ ] Redux Debug
- [ ] Sentry Message
- [ ] Sentry Exception

### Integrated but not visible
- [ ] Bus Map
