### ISSUE TITLE
v2.2 Tracking Issue

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/AAO-React-Native#935]
Things we want to do before we release v2.2 [[milestone](https://github.com/StoDevX/AAO-React-Native/milestone/6)]:

- [x] Remove Presence calendar (#933)
- [x] Call codePush.sync in the root component (#966)
- [x] Merge the "link rn-maps" PR (#897)
- [x] Fix menu filters (#908)
- [x] Disable the Courses tab (#978)
- [x] Add quick wifi-reporting feature (https://github.com/StoDevX/AAO-React-Native/issues/934)
- [x] Searching the AlphabetListViews crashes the app (#1001)

Anything else, @elijahverdoorn @drewvolz?

---

I have compiled some release notes for v2.2 in the wiki: https://github.com/StoDevX/AAO-React-Native/wiki/Release-Notes

**Comment by hawkrives** [comment]
Skimming old issues, I found https://github.com/StoDevX/AAO-React-Native/issues/401 (the "we can't log into SIS after April 17th" issue.)

`master` no longer uses the SIS for financial info, but we won't be able to fill out the Courses tab once Google disables the in-app browser OAuth login.

So I'd like to figure out what to do about the Courses tab before v2.2.

**Comment by elijahverdoorn** [comment]
If there was ever a time that it would be convenient to remove the courses view (temporarily, of course), now is the time as registration just closed and most students have their schedule memorized. If we get an update out by the 17th, we can avoid confusing users by just hiding the screen, then add it back if/when we get a data source again.

I'm going to do a run-through of the building hours data again, I think that some of them may be wrong based on some of the comments I've gotten.

**Comment by drewvolz** [comment]
I've added the issue related to Presence orgs to the list.

**Comment by hawkrives** [comment]
I'm going to take presence's orgs back off the list – I've got a _goal_ of being able to replace it with an /orgs/list endpoint, before they shut us down, but even if I can't there's no reason to remove it _now_ vs later via codepush?

**Comment by hawkrives** [comment]
We should solve https://github.com/StoDevX/AAO-React-Native/issues/908 as part of 2.2

**Comment by hawkrives** [comment]
There are no issues that I know of blocking the release of v2.2.

**Comment by drewvolz** [comment]
How should we approach search crashing the AlphabetListView? It seems like an issue for 2.2

**Comment by hawkrives** [comment]
Have you tried lodash's debounce method yet?

**Comment by drewvolz** [comment]
Not yet. Good reminder.

**Comment by hawkrives** [comment]
I added #1001 to the tracking list and the milestone.

**Comment by hawkrives** [comment]
There are no more blocking issues that I know of. 

Drew and I will test the app thoroughly after tonight's beta.

**Comment by hawkrives** [comment]
Said beta had some big issues. I've reverted the change that caused them.

**Comment by hawkrives** [comment]
I have begun deploying v2.2-beta.2 (and v2.2-beta.1, but I forgot to let travis build the tag so I made a new tag.)

Drew and I will test this on iOS today.

@elijahverdoorn, can you/your team start poking at it on Android? (or @drewvolz, didn't you get an android phone?)

Also @elijahverdoorn – what's your timeline now that the weekend is past?

**Comment by hawkrives** [comment]
@elijahverdoorn I just noticed that you mentioned incorrect building hours in https://github.com/StoDevX/AAO-React-Native/issues/935#issuecomment-293356732 – have you had a chance to look into that?

**Comment by hawkrives** [comment]
2.2.0 Beta 5 is now entering testing. I'm trying to make sure codepush deployments are working.

**Comment by hawkrives** [comment]
Now attempting beta 6, to see if Codepush will properly deploy a new release this time. (https://github.com/StoDevX/AAO-React-Native/pull/1048 was _an_ issue, but let's see if it was the _only_ problem.)

**Comment by hawkrives** [comment]
I'm going to release beta 7, primarily to incorporate #1053, but also to make sure it doesn't crash with #1055.

**Comment by elijahverdoorn** [comment]
@hawkrives Haven't had a chance yet, I'll get it out over codepush... I want to get this release done so that I can FINALLY stop holding you and @drewvolz up.

**Comment by hawkrives** [comment]
Alrighty! 

Beta 7 is stable, fyi.

**Comment by hawkrives** [comment]
I'm going to kick off a v2.2.1 build and submit to testflight.

@elijahverdoorn, I still need the Google Play login info :-)

**Comment by hawkrives** [comment]
I'm going to keep this open until 2.2 is fully released.

**Comment by hawkrives** [comment]
We had an app rejection from Apple because we mentioned "Android" in our release notes. 

- I removed all mentions of Android from the release notes
- I will go update the wiki page on release notes to support separate iOS/Android sections
- I have re-submitted the app

**Comment by hawkrives** [comment]
I'm going to close this, as v2.2 is now out for iOS, and android is just waiting for a few more people to make sure it works properly!
